### ISSUE TITLE
Nginx reverse proxy settings

### ISSUE THREAD

**Issue by douglagm** [microsoft/CloudAdoptionFramework#138]
Hi,

Is there an nginx reverse proxy config? I have spent days trying many, many different configurations, some work better than others, but none seem to work 100%. So, I was wondering if someone can share their config? We can then keep this thread for others that require the same.

Regards

**Comment by douglagm** [comment]
I broke the tool. Re-installed, but still get can't get it to work, this is without nginx reverse proxy:

`warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: The key {b92498b4-814a-4a66-baab-4f8dc3e613d6} was not found in the key ring. For more information go to http://aka.ms/dataprotectionwarning
      System.Security.Cryptography.CryptographicException: The key {b92498b4-814a-4a66-baab-4f8dc3e613d6} was not found in the key ring. For more information go to http://aka.ms/dataprotectionwarning
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
         at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
         at Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage.ProtectedBrowserStorage.Unprotect[TValue](String purpose, String protectedJson)
         at Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage.ProtectedBrowserStorage.GetAsync[TValue](String purpose, String key)
         at AzureNamingTool.Shared.MainLayout.OnAfterRenderAsync(Boolean firstRender) in /src/Shared/MainLayout.razor:line 84
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'L2RMv-sHDA2hmrxya9LQMjtwLTA225WecSVpqyYBgY8'.
      System.Security.Cryptography.CryptographicException: The key {b92498b4-814a-4a66-baab-4f8dc3e613d6} was not found in the key ring. For more information go to http://aka.ms/dataprotectionwarning
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
         at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
         at Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage.ProtectedBrowserStorage.Unprotect[TValue](String purpose, String protectedJson)
         at Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage.ProtectedBrowserStorage.GetAsync[TValue](String purpose, String key)
         at AzureNamingTool.Shared.MainLayout.OnAfterRenderAsync(Boolean firstRender) in /src/Shared/MainLayout.razor:line 84
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
`

**Comment by Zimmergren** [comment]
Unrelated to CAF content. 
No activity from the author since opening in February 2023. Closing.
